[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
crowdfi = "14QSPRYYb9EyDHSXsqCNY4mcWKQ6dRycb8SNXeKHUcm4"

[programs.devnet]
crowdfi = "14QSPRYYb9EyDHSXsqCNY4mcWKQ6dRycb8SNXeKHUcm4"

[programs.mainnet]
crowdfi = "14QSPRYYb9EyDHSXsqCNY4mcWKQ6dRycb8SNXeKHUcm4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 __tests__/**/*.ts"
# test = "yarn test"